version: "3.9"
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
